#!/usr/bin/env python3
import argparse
from mlir_onnx import ONNX

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='ONNX to MLIR Converter')
    parser.add_argument('-o', '--output', dest='output', type=str, required=True,
                        metavar='MLIR', help='output(MLIR) file path')
    parser.add_argument(dest='input', type=str,
                        metavar='ONNX', help='input(ONNX) file path')
    args = parser.parse_args()
    ONNX(args.input).to_MLIR().dump(args.output)
