[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = false  # disabled due to too many errors
enable_isort = true
enable_mypy = false    # disabled currently
mypy_preset = "strict"
line_length = 128
py_version = "py37"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
