#!/usr/bin/env python3
import argparse
import onnx
import sys
from nnoir_onnx import ONNX, utils

def check_graph(input_path):
    model = onnx.load(input_path)
    vs = utils.list_dimension_variables(model)
    if len(vs) != 0:
        sys.exit(f"""Error: This ONNX model includes dimension variables.
{vs}
Set the values with `freeze_onnx freeze`.
$ freeze_onnx freeze --help""")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='ONNX to NNOIR Converter')
    parser.add_argument('-o', '--output', dest='output', type=str, required=True,
                        metavar='NNOIR', help='output(NNOIR) file path')
    parser.add_argument(dest='input', type=str,
                        metavar='ONNX', help='input(ONNX) file path')
    args = parser.parse_args()
    check_graph(args.input)
    ONNX(args.input).to_NNOIR().dump(args.output)
