import nnoir_chainer.links.connection.convolution_2d
import nnoir_chainer.links.connection.depthwise_convolution_2d
import nnoir_chainer.links.connection.dilated_convolution_2d
import nnoir_chainer.links.connection.linear
import nnoir_chainer.links.connection.lstm
import nnoir_chainer.links.connection.scale
import nnoir_chainer.links.connection.bias
